using System;
using Unity.Mathematics;

namespace jedjoud.VoxelTerrain.Generation {
    public abstract partial class Variable<T> : UntypedVariable {
        private void VerifyAllowedSwizzle(int index) {
            if ((index + 1) > VariableType.Dimensionality<T>()) {
                throw new Exception("Trying to swizzle at a higher dimension than possible");
            }
        }

        public Variable<float> x { get { VerifyAllowedSwizzle(0); return new SwizzleNode<T, float> { a = this, swizzle = "x" }; } }
        public Variable<float> y { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float> { a = this, swizzle = "y" }; } }
        public Variable<float> z { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float> { a = this, swizzle = "z" }; } }
        public Variable<float> w { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float> { a = this, swizzle = "w" }; } }
        public Variable<float2> xx { get { VerifyAllowedSwizzle(0); return new SwizzleNode<T, float2> { a = this, swizzle = "xx" }; } }
        public Variable<float2> xy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float2> { a = this, swizzle = "xy" }; } }
        public Variable<float2> xz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float2> { a = this, swizzle = "xz" }; } }
        public Variable<float2> xw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float2> { a = this, swizzle = "xw" }; } }
        public Variable<float2> yx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float2> { a = this, swizzle = "yx" }; } }
        public Variable<float2> yy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float2> { a = this, swizzle = "yy" }; } }
        public Variable<float2> yz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float2> { a = this, swizzle = "yz" }; } }
        public Variable<float2> yw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float2> { a = this, swizzle = "yw" }; } }
        public Variable<float2> zx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float2> { a = this, swizzle = "zx" }; } }
        public Variable<float2> zy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float2> { a = this, swizzle = "zy" }; } }
        public Variable<float2> zz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float2> { a = this, swizzle = "zz" }; } }
        public Variable<float2> zw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float2> { a = this, swizzle = "zw" }; } }
        public Variable<float2> wx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float2> { a = this, swizzle = "wx" }; } }
        public Variable<float2> wy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float2> { a = this, swizzle = "wy" }; } }
        public Variable<float2> wz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float2> { a = this, swizzle = "wz" }; } }
        public Variable<float2> ww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float2> { a = this, swizzle = "ww" }; } }
        public Variable<float3> xxx { get { VerifyAllowedSwizzle(0); return new SwizzleNode<T, float3> { a = this, swizzle = "xxx" }; } }
        public Variable<float3> xxy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float3> { a = this, swizzle = "xxy" }; } }
        public Variable<float3> xxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "xxz" }; } }
        public Variable<float3> xxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "xxw" }; } }
        public Variable<float3> xyx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float3> { a = this, swizzle = "xyx" }; } }
        public Variable<float3> xyy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float3> { a = this, swizzle = "xyy" }; } }
        public Variable<float3> xyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "xyz" }; } }
        public Variable<float3> xyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "xyw" }; } }
        public Variable<float3> xzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "xzx" }; } }
        public Variable<float3> xzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "xzy" }; } }
        public Variable<float3> xzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "xzz" }; } }
        public Variable<float3> xzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "xzw" }; } }
        public Variable<float3> xwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "xwx" }; } }
        public Variable<float3> xwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "xwy" }; } }
        public Variable<float3> xwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "xwz" }; } }
        public Variable<float3> xww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "xww" }; } }
        public Variable<float3> yxx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float3> { a = this, swizzle = "yxx" }; } }
        public Variable<float3> yxy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float3> { a = this, swizzle = "yxy" }; } }
        public Variable<float3> yxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "yxz" }; } }
        public Variable<float3> yxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "yxw" }; } }
        public Variable<float3> yyx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float3> { a = this, swizzle = "yyx" }; } }
        public Variable<float3> yyy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float3> { a = this, swizzle = "yyy" }; } }
        public Variable<float3> yyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "yyz" }; } }
        public Variable<float3> yyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "yyw" }; } }
        public Variable<float3> yzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "yzx" }; } }
        public Variable<float3> yzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "yzy" }; } }
        public Variable<float3> yzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "yzz" }; } }
        public Variable<float3> yzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "yzw" }; } }
        public Variable<float3> ywx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "ywx" }; } }
        public Variable<float3> ywy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "ywy" }; } }
        public Variable<float3> ywz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "ywz" }; } }
        public Variable<float3> yww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "yww" }; } }
        public Variable<float3> zxx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zxx" }; } }
        public Variable<float3> zxy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zxy" }; } }
        public Variable<float3> zxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zxz" }; } }
        public Variable<float3> zxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "zxw" }; } }
        public Variable<float3> zyx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zyx" }; } }
        public Variable<float3> zyy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zyy" }; } }
        public Variable<float3> zyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zyz" }; } }
        public Variable<float3> zyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "zyw" }; } }
        public Variable<float3> zzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zzx" }; } }
        public Variable<float3> zzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zzy" }; } }
        public Variable<float3> zzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float3> { a = this, swizzle = "zzz" }; } }
        public Variable<float3> zzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "zzw" }; } }
        public Variable<float3> zwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "zwx" }; } }
        public Variable<float3> zwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "zwy" }; } }
        public Variable<float3> zwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "zwz" }; } }
        public Variable<float3> zww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "zww" }; } }
        public Variable<float3> wxx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wxx" }; } }
        public Variable<float3> wxy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wxy" }; } }
        public Variable<float3> wxz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wxz" }; } }
        public Variable<float3> wxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wxw" }; } }
        public Variable<float3> wyx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wyx" }; } }
        public Variable<float3> wyy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wyy" }; } }
        public Variable<float3> wyz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wyz" }; } }
        public Variable<float3> wyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wyw" }; } }
        public Variable<float3> wzx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wzx" }; } }
        public Variable<float3> wzy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wzy" }; } }
        public Variable<float3> wzz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wzz" }; } }
        public Variable<float3> wzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wzw" }; } }
        public Variable<float3> wwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wwx" }; } }
        public Variable<float3> wwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wwy" }; } }
        public Variable<float3> wwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "wwz" }; } }
        public Variable<float3> www { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float3> { a = this, swizzle = "www" }; } }
        public Variable<float4> xxxx { get { VerifyAllowedSwizzle(0); return new SwizzleNode<T, float4> { a = this, swizzle = "xxxx" }; } }
        public Variable<float4> xxxy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "xxxy" }; } }
        public Variable<float4> xxxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xxxz" }; } }
        public Variable<float4> xxxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xxxw" }; } }
        public Variable<float4> xxyx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "xxyx" }; } }
        public Variable<float4> xxyy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "xxyy" }; } }
        public Variable<float4> xxyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xxyz" }; } }
        public Variable<float4> xxyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xxyw" }; } }
        public Variable<float4> xxzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xxzx" }; } }
        public Variable<float4> xxzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xxzy" }; } }
        public Variable<float4> xxzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xxzz" }; } }
        public Variable<float4> xxzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xxzw" }; } }
        public Variable<float4> xxwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xxwx" }; } }
        public Variable<float4> xxwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xxwy" }; } }
        public Variable<float4> xxwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xxwz" }; } }
        public Variable<float4> xxww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xxww" }; } }
        public Variable<float4> xyxx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "xyxx" }; } }
        public Variable<float4> xyxy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "xyxy" }; } }
        public Variable<float4> xyxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xyxz" }; } }
        public Variable<float4> xyxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xyxw" }; } }
        public Variable<float4> xyyx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "xyyx" }; } }
        public Variable<float4> xyyy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "xyyy" }; } }
        public Variable<float4> xyyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xyyz" }; } }
        public Variable<float4> xyyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xyyw" }; } }
        public Variable<float4> xyzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xyzx" }; } }
        public Variable<float4> xyzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xyzy" }; } }
        public Variable<float4> xyzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xyzz" }; } }
        public Variable<float4> xyzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xyzw" }; } }
        public Variable<float4> xywx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xywx" }; } }
        public Variable<float4> xywy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xywy" }; } }
        public Variable<float4> xywz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xywz" }; } }
        public Variable<float4> xyww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xyww" }; } }
        public Variable<float4> xzxx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzxx" }; } }
        public Variable<float4> xzxy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzxy" }; } }
        public Variable<float4> xzxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzxz" }; } }
        public Variable<float4> xzxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xzxw" }; } }
        public Variable<float4> xzyx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzyx" }; } }
        public Variable<float4> xzyy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzyy" }; } }
        public Variable<float4> xzyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzyz" }; } }
        public Variable<float4> xzyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xzyw" }; } }
        public Variable<float4> xzzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzzx" }; } }
        public Variable<float4> xzzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzzy" }; } }
        public Variable<float4> xzzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "xzzz" }; } }
        public Variable<float4> xzzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xzzw" }; } }
        public Variable<float4> xzwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xzwx" }; } }
        public Variable<float4> xzwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xzwy" }; } }
        public Variable<float4> xzwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xzwz" }; } }
        public Variable<float4> xzww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xzww" }; } }
        public Variable<float4> xwxx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwxx" }; } }
        public Variable<float4> xwxy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwxy" }; } }
        public Variable<float4> xwxz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwxz" }; } }
        public Variable<float4> xwxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwxw" }; } }
        public Variable<float4> xwyx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwyx" }; } }
        public Variable<float4> xwyy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwyy" }; } }
        public Variable<float4> xwyz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwyz" }; } }
        public Variable<float4> xwyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwyw" }; } }
        public Variable<float4> xwzx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwzx" }; } }
        public Variable<float4> xwzy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwzy" }; } }
        public Variable<float4> xwzz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwzz" }; } }
        public Variable<float4> xwzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwzw" }; } }
        public Variable<float4> xwwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwwx" }; } }
        public Variable<float4> xwwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwwy" }; } }
        public Variable<float4> xwwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwwz" }; } }
        public Variable<float4> xwww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "xwww" }; } }
        public Variable<float4> yxxx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "yxxx" }; } }
        public Variable<float4> yxxy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "yxxy" }; } }
        public Variable<float4> yxxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yxxz" }; } }
        public Variable<float4> yxxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yxxw" }; } }
        public Variable<float4> yxyx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "yxyx" }; } }
        public Variable<float4> yxyy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "yxyy" }; } }
        public Variable<float4> yxyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yxyz" }; } }
        public Variable<float4> yxyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yxyw" }; } }
        public Variable<float4> yxzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yxzx" }; } }
        public Variable<float4> yxzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yxzy" }; } }
        public Variable<float4> yxzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yxzz" }; } }
        public Variable<float4> yxzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yxzw" }; } }
        public Variable<float4> yxwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yxwx" }; } }
        public Variable<float4> yxwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yxwy" }; } }
        public Variable<float4> yxwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yxwz" }; } }
        public Variable<float4> yxww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yxww" }; } }
        public Variable<float4> yyxx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "yyxx" }; } }
        public Variable<float4> yyxy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "yyxy" }; } }
        public Variable<float4> yyxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yyxz" }; } }
        public Variable<float4> yyxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yyxw" }; } }
        public Variable<float4> yyyx { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "yyyx" }; } }
        public Variable<float4> yyyy { get { VerifyAllowedSwizzle(1); return new SwizzleNode<T, float4> { a = this, swizzle = "yyyy" }; } }
        public Variable<float4> yyyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yyyz" }; } }
        public Variable<float4> yyyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yyyw" }; } }
        public Variable<float4> yyzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yyzx" }; } }
        public Variable<float4> yyzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yyzy" }; } }
        public Variable<float4> yyzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yyzz" }; } }
        public Variable<float4> yyzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yyzw" }; } }
        public Variable<float4> yywx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yywx" }; } }
        public Variable<float4> yywy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yywy" }; } }
        public Variable<float4> yywz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yywz" }; } }
        public Variable<float4> yyww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yyww" }; } }
        public Variable<float4> yzxx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzxx" }; } }
        public Variable<float4> yzxy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzxy" }; } }
        public Variable<float4> yzxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzxz" }; } }
        public Variable<float4> yzxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yzxw" }; } }
        public Variable<float4> yzyx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzyx" }; } }
        public Variable<float4> yzyy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzyy" }; } }
        public Variable<float4> yzyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzyz" }; } }
        public Variable<float4> yzyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yzyw" }; } }
        public Variable<float4> yzzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzzx" }; } }
        public Variable<float4> yzzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzzy" }; } }
        public Variable<float4> yzzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "yzzz" }; } }
        public Variable<float4> yzzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yzzw" }; } }
        public Variable<float4> yzwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yzwx" }; } }
        public Variable<float4> yzwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yzwy" }; } }
        public Variable<float4> yzwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yzwz" }; } }
        public Variable<float4> yzww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "yzww" }; } }
        public Variable<float4> ywxx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywxx" }; } }
        public Variable<float4> ywxy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywxy" }; } }
        public Variable<float4> ywxz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywxz" }; } }
        public Variable<float4> ywxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywxw" }; } }
        public Variable<float4> ywyx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywyx" }; } }
        public Variable<float4> ywyy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywyy" }; } }
        public Variable<float4> ywyz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywyz" }; } }
        public Variable<float4> ywyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywyw" }; } }
        public Variable<float4> ywzx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywzx" }; } }
        public Variable<float4> ywzy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywzy" }; } }
        public Variable<float4> ywzz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywzz" }; } }
        public Variable<float4> ywzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywzw" }; } }
        public Variable<float4> ywwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywwx" }; } }
        public Variable<float4> ywwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywwy" }; } }
        public Variable<float4> ywwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywwz" }; } }
        public Variable<float4> ywww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "ywww" }; } }
        public Variable<float4> zxxx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxxx" }; } }
        public Variable<float4> zxxy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxxy" }; } }
        public Variable<float4> zxxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxxz" }; } }
        public Variable<float4> zxxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zxxw" }; } }
        public Variable<float4> zxyx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxyx" }; } }
        public Variable<float4> zxyy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxyy" }; } }
        public Variable<float4> zxyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxyz" }; } }
        public Variable<float4> zxyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zxyw" }; } }
        public Variable<float4> zxzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxzx" }; } }
        public Variable<float4> zxzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxzy" }; } }
        public Variable<float4> zxzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zxzz" }; } }
        public Variable<float4> zxzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zxzw" }; } }
        public Variable<float4> zxwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zxwx" }; } }
        public Variable<float4> zxwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zxwy" }; } }
        public Variable<float4> zxwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zxwz" }; } }
        public Variable<float4> zxww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zxww" }; } }
        public Variable<float4> zyxx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyxx" }; } }
        public Variable<float4> zyxy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyxy" }; } }
        public Variable<float4> zyxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyxz" }; } }
        public Variable<float4> zyxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zyxw" }; } }
        public Variable<float4> zyyx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyyx" }; } }
        public Variable<float4> zyyy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyyy" }; } }
        public Variable<float4> zyyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyyz" }; } }
        public Variable<float4> zyyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zyyw" }; } }
        public Variable<float4> zyzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyzx" }; } }
        public Variable<float4> zyzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyzy" }; } }
        public Variable<float4> zyzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zyzz" }; } }
        public Variable<float4> zyzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zyzw" }; } }
        public Variable<float4> zywx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zywx" }; } }
        public Variable<float4> zywy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zywy" }; } }
        public Variable<float4> zywz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zywz" }; } }
        public Variable<float4> zyww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zyww" }; } }
        public Variable<float4> zzxx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzxx" }; } }
        public Variable<float4> zzxy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzxy" }; } }
        public Variable<float4> zzxz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzxz" }; } }
        public Variable<float4> zzxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zzxw" }; } }
        public Variable<float4> zzyx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzyx" }; } }
        public Variable<float4> zzyy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzyy" }; } }
        public Variable<float4> zzyz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzyz" }; } }
        public Variable<float4> zzyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zzyw" }; } }
        public Variable<float4> zzzx { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzzx" }; } }
        public Variable<float4> zzzy { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzzy" }; } }
        public Variable<float4> zzzz { get { VerifyAllowedSwizzle(2); return new SwizzleNode<T, float4> { a = this, swizzle = "zzzz" }; } }
        public Variable<float4> zzzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zzzw" }; } }
        public Variable<float4> zzwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zzwx" }; } }
        public Variable<float4> zzwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zzwy" }; } }
        public Variable<float4> zzwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zzwz" }; } }
        public Variable<float4> zzww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zzww" }; } }
        public Variable<float4> zwxx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwxx" }; } }
        public Variable<float4> zwxy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwxy" }; } }
        public Variable<float4> zwxz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwxz" }; } }
        public Variable<float4> zwxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwxw" }; } }
        public Variable<float4> zwyx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwyx" }; } }
        public Variable<float4> zwyy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwyy" }; } }
        public Variable<float4> zwyz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwyz" }; } }
        public Variable<float4> zwyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwyw" }; } }
        public Variable<float4> zwzx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwzx" }; } }
        public Variable<float4> zwzy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwzy" }; } }
        public Variable<float4> zwzz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwzz" }; } }
        public Variable<float4> zwzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwzw" }; } }
        public Variable<float4> zwwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwwx" }; } }
        public Variable<float4> zwwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwwy" }; } }
        public Variable<float4> zwwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwwz" }; } }
        public Variable<float4> zwww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "zwww" }; } }
        public Variable<float4> wxxx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxxx" }; } }
        public Variable<float4> wxxy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxxy" }; } }
        public Variable<float4> wxxz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxxz" }; } }
        public Variable<float4> wxxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxxw" }; } }
        public Variable<float4> wxyx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxyx" }; } }
        public Variable<float4> wxyy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxyy" }; } }
        public Variable<float4> wxyz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxyz" }; } }
        public Variable<float4> wxyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxyw" }; } }
        public Variable<float4> wxzx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxzx" }; } }
        public Variable<float4> wxzy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxzy" }; } }
        public Variable<float4> wxzz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxzz" }; } }
        public Variable<float4> wxzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxzw" }; } }
        public Variable<float4> wxwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxwx" }; } }
        public Variable<float4> wxwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxwy" }; } }
        public Variable<float4> wxwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxwz" }; } }
        public Variable<float4> wxww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wxww" }; } }
        public Variable<float4> wyxx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyxx" }; } }
        public Variable<float4> wyxy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyxy" }; } }
        public Variable<float4> wyxz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyxz" }; } }
        public Variable<float4> wyxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyxw" }; } }
        public Variable<float4> wyyx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyyx" }; } }
        public Variable<float4> wyyy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyyy" }; } }
        public Variable<float4> wyyz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyyz" }; } }
        public Variable<float4> wyyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyyw" }; } }
        public Variable<float4> wyzx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyzx" }; } }
        public Variable<float4> wyzy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyzy" }; } }
        public Variable<float4> wyzz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyzz" }; } }
        public Variable<float4> wyzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyzw" }; } }
        public Variable<float4> wywx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wywx" }; } }
        public Variable<float4> wywy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wywy" }; } }
        public Variable<float4> wywz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wywz" }; } }
        public Variable<float4> wyww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wyww" }; } }
        public Variable<float4> wzxx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzxx" }; } }
        public Variable<float4> wzxy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzxy" }; } }
        public Variable<float4> wzxz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzxz" }; } }
        public Variable<float4> wzxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzxw" }; } }
        public Variable<float4> wzyx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzyx" }; } }
        public Variable<float4> wzyy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzyy" }; } }
        public Variable<float4> wzyz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzyz" }; } }
        public Variable<float4> wzyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzyw" }; } }
        public Variable<float4> wzzx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzzx" }; } }
        public Variable<float4> wzzy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzzy" }; } }
        public Variable<float4> wzzz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzzz" }; } }
        public Variable<float4> wzzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzzw" }; } }
        public Variable<float4> wzwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzwx" }; } }
        public Variable<float4> wzwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzwy" }; } }
        public Variable<float4> wzwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzwz" }; } }
        public Variable<float4> wzww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wzww" }; } }
        public Variable<float4> wwxx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwxx" }; } }
        public Variable<float4> wwxy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwxy" }; } }
        public Variable<float4> wwxz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwxz" }; } }
        public Variable<float4> wwxw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwxw" }; } }
        public Variable<float4> wwyx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwyx" }; } }
        public Variable<float4> wwyy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwyy" }; } }
        public Variable<float4> wwyz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwyz" }; } }
        public Variable<float4> wwyw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwyw" }; } }
        public Variable<float4> wwzx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwzx" }; } }
        public Variable<float4> wwzy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwzy" }; } }
        public Variable<float4> wwzz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwzz" }; } }
        public Variable<float4> wwzw { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwzw" }; } }
        public Variable<float4> wwwx { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwwx" }; } }
        public Variable<float4> wwwy { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwwy" }; } }
        public Variable<float4> wwwz { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwwz" }; } }
        public Variable<float4> wwww { get { VerifyAllowedSwizzle(3); return new SwizzleNode<T, float4> { a = this, swizzle = "wwww" }; } }
    }
}