#pragma kernel CSApply

#define UNITY_INDIRECT_DRAW_ARGS IndirectDrawIndexedArgs
#include "UnityIndirect.cginc"

RWStructuredBuffer<UNITY_INDIRECT_DRAW_ARGS> draw_args_buffer;
RWStructuredBuffer<uint> visible_props_counters_buffer;

[numthreads(1, 1, 1)]
void CSApply(uint3 id : SV_DispatchThreadID) {
	IndirectDrawIndexedArgs args = draw_args_buffer[id.x];
	args.instanceCount = visible_props_counters_buffer[id.x];
	draw_args_buffer[id.x] = args;
}